### ISSUE TITLE
Testing on BOP 2023 error

### ISSUE THREAD

**Issue by michalt38** [nv-nguyen/gigapose#20]
While running a prediction with the command `python test.py test_dataset_name=lmo` I am having the following error:

```
Error executing job with overrides: ['test_dataset_name=lmo']
Traceback (most recent call last):
  File "/opt/conda/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src.models' has no attribute 'gigaPose'
```

Do you know how to fix that?

**Comment by CQUChenC** [comment]
Hello, I encountered the same problem. Did you manage to solve it? :"hydra.errors.InstantiationException: Error locating target 'src.models.gigaPose.GigaPose"
