### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by kordou** [nv-nguyen/gigapose#4]
hi,
i am a student on a master for ML and i have an assignement to findd and run some 6DPose estimation models.
i tryed to install your on windos with cuda 12 but i cannot even install the code

 i get 
Installing collected packages: pypng, PyOpenGL, hsluv, freetype-py, cython, vispy, bop-toolkit-lib
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tables 3.8.0 requires blosc2~=2.0.0, which is not installed.

i tryed to install the tables and block2 but seems that there are not exist 

and later in 

python -m src.scripts.download_test
i get erros
ModuleNotFoundError: No module named 'hydra'

and again if  try to install manually

Downloading Hydra-2.5.tar.gz (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.4/82.4 kB 386.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: hydra
  Building wheel for hydra (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
  ...
   cl : Command line warning D9002 : ignoring unknown option '-std=gnu99'
      _hydra.c
      src/_hydra.c(61): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hydra
  Running setup.py clean for hydra
Failed to build hydra
ERROR: Could not build wheels for hydra, which is required to install pyproject.toml-based projects

coudl you provide a way to install it

thank you in advanced

**Comment by nv-nguyen** [comment]
Could you please share me the output of the command below?

`conda env create -f environment.yml`

Since hydra has been already included in `environment.yml`, so I am wondering what is happening

**Comment by kordou** [comment]
i manages to install it. widnows did not recognise the bach and when i make it maually the erro gone.

is there any way to run a demo in my pc withot having to train ?  ia am  astudent in ML a just started my master and i have an assignment ro just run some models and ge the time and effilicenty . 

thank you in advanved

**Comment by nv-nguyen** [comment]
GigaPose can be applied on any objects without re-training.  

I closed the issue since it is not related to installation errors but the demo (duplicated #3).
