### ISSUE TITLE
Sampling templates from isosphere

### ISSUE THREAD

**Issue by DanieleBertagnoli** [nv-nguyen/gigapose#6]
Hi, I'm a computer science student and I'm interested in studying your methodology. When I try to execute the create_template_poses.py using blenderproc, according to the prints in the code, it says that the camera location is parallel to tmp. Since no input are needed I guess that these warnings are not due to my setup (I hope at least). It is normal that I receive that warnings or I have to change something? 

Moreover, I was investigating on the level0 and level2 that seem to be unused. I read in the paper that you decided to use 162 templates as compromise between performance and accuracy, therefore those two levels are there as residuals from the testing?

Thank you, for the attention!

**Comment by nv-nguyen** [comment]
It is normal that you have this warning and you do not need to change anything.

About the number of templates, yes, only level1 with 162 for the tradeoff accuracy-runtime (and also memory required).

Hope it helps!

**Comment by DanieleBertagnoli** [comment]
Yes it was very helpfull, thank you!
