### ISSUE TITLE
key_to_shard.json file

### ISSUE THREAD

**Issue by MarcoGuarino** [nv-nguyen/gigapose#8]
Hi, I was examining the class GigaPoseTrainSet that implements the data loader. When loading the datasets for training, what it downloads is key_to_shard.json and the various shards. What do the values in key_to_shard.json represent?
Thank you in adavanced !

**Comment by nv-nguyen** [comment]
All the datasets used in GigaPose are taken from [BOP challenge 2023](https://bop.felk.cvut.cz/challenges/bop-challenge-2023/).

`key_to_shard.json` represents the mapping from image_key to shard_id which is mentioned [here](https://github.com/thodan/bop_toolkit/blob/master/docs/bop_challenge_2023_training_datasets.md).
